name: mg

channels:
  - conda-forge
  - metagraph/label/dev

dependencies:
  - python=3.8
  - coverage
  - pytest
  - pytest-cov
  - black >=20.8b1
  - setuptools

# metagraph-cogdl dependencies
  - cogdl
  - metagraph >=0.2.3
